Калькулятор
TimurMamdov1991/TimurMamedov_LevelUp pull request #1
Opened 2020-04-19 13:06 UTC by TimurMamdov1991

По требованиям:
Сложение + (int, Double)
Вычитание + (int, Double)
Умножение + (int, Double)
Возведение в степень + (int)
факториала числа + (int)
Фибоначчи + (int)

2020-04-22 15:57 UTC, khda91 requested changes
Please resolve comments

2020-04-22 15:57 UTC, khda91 commented on pom.xml
> +                </configuration>
Почему `target` &`source` версии Java установлены для 7-ой версии?

2020-04-22 15:57 UTC, khda91 commented on src/main/java/homework_number/task_1/Addition.java
> +  }
Соблюдай, пожалуйста, **Java Code Convention** для наименования методов, переменных, полей, классов

2020-04-22 15:57 UTC, khda91 commented on src/main/java/homework_number/task_1/Exponentiation.java
> +  }
Соблюдай, пожалуйста, **Java Code Convention** для наименования методов, переменных, полей, классов

2020-04-22 15:57 UTC, khda91 commented on src/main/java/homework_number/task_1/Exponentiation.java
> +public class Exponentiation {
Какую операцию выполняет данный класс?

2020-04-22 15:57 UTC, khda91 commented on src/main/java/homework_number/task_1/Factorial.java
> +  }
Соблюдай, пожалуйста, **Java Code Convention** для наименования методов, переменных, полей, классов

2020-04-22 15:57 UTC, khda91 commented on src/main/java/homework_number/task_1/Multiplication.java
> +  }
Соблюдай, пожалуйста, **Java Code Convention** для наименования методов, переменных, полей, классов

2020-04-22 15:57 UTC, khda91 commented on src/main/java/homework_number/task_1/Subtraction.java
> +  }
Соблюдай, пожалуйста, **Java Code Convention** для наименования методов, переменных, полей, классов

2020-04-26 14:52 UTC, TimurMamdov1991 commented on src/main/java/homework_number/task_1/Exponentiation.java
> +public class Exponentiation {
Возведение в степень

2020-04-26 15:24 UTC, TimurMamdov1991 commented on src/main/java/homework_number/task_1/Addition.java
> +  }
поменял на fold

2020-04-27 22:05 UTC, khda91 commented on pom.xml
> +                </configuration>
Комментарий пропущен

2020-04-27 22:05 UTC, khda91 commented on src/main/java/homework_number/task_1/Addition.java
> +  }
Окей, с методом разобрались, остались параметры

2020-04-27 22:08 UTC, khda91 commented on src/main/java/homework_number/task_1/Degree.java
> +public class Degree {
Не вижу возвидения в степень, есть только возведение в квадрат

2020-04-27 22:08 UTC, khda91 commented on src/main/java/homework_number/task_1/Factorial.java
> +  }
Какой стиль для названия переменных используется?

2020-04-27 22:08 UTC, khda91 requested changes
Пожалуйста, исправьте комментарии

2020-04-28 10:52 UTC, TimurMamdov1991 commented on pom.xml
> +                </configuration>
Забыл изначально поменять на 8

2020-04-28 12:33 UTC, TimurMamdov1991 commented on src/main/java/homework_number/task_1/Exponentiation.java
> +  }
исправил

2020-04-28 12:34 UTC, TimurMamdov1991 commented on src/main/java/homework_number/task_1/Factorial.java
> +  }
Стиль название для переменных это глаголы

2020-04-28 15:06 UTC, khda91 approved these changes
Принята

2020-05-15 07:26 UTC, merged