Homework 3
TimurMamdov1991/TimurMamedov_LevelUp pull request #4
Opened 2020-05-11 23:55 UTC by TimurMamdov1991

2020-05-14 22:42 UTC, khda91 requested changes
Исправить комментарии

2020-05-14 22:42 UTC, khda91 commented on pom.xml
> +        <dependency>
1. проект не собирается
2. почему подключены все 3 test framework?

2020-05-15 21:48 UTC, TimurMamdov1991 commented on pom.xml
> +        <dependency>
убрал лишнее

2020-05-21 23:10 UTC, khda91 requested changes
Проект не собирается

2020-05-21 23:10 UTC, khda91 commented on pom.xml
> +    <dependencies>
Библиотека калькулятора отсутствует в зависимостях. Нужно добавить её в pom файл, чтобы проект собирался

2020-05-26 21:26 UTC, khda91 approved these changes
Работа принята

2020-05-29 11:15 UTC, closed without merging